export const SURAHS_LIST = [
  { number: 1, name: "الفاتحة", englishName: "Al-Fatihah", urduName: "سورۃ الفاتحہ", englishMeaning: "The Opening", ayahs: 7, type: "Meccan", juz: 1 },
  { number: 2, name: "البقرة", englishName: "Al-Baqarah", urduName: "سورۃ البقرہ", englishMeaning: "The Cow", ayahs: 286, type: "Medinan", juz: 1 },
  { number: 3, name: "آل عمران", englishName: "Ali 'Imran", urduName: "سورۃ آل عمران", englishMeaning: "The Family of Imran", ayahs: 200, type: "Medinan" },
  { number: 4, name: "النساء", englishName: "An-Nisa", urduName: "سورۃ النساء", englishMeaning: "The Women", ayahs: 176, type: "Medinan" },
  { number: 5, name: "المائدة", englishName: "Al-Ma'idah", urduName: "سورۃ المائدہ", englishMeaning: "The Table Spread", ayahs: 120, type: "Medinan" },
  { number: 6, name: "الأنعام", englishName: "Al-An'am", urduName: "سورۃ الانعام", englishMeaning: "The Cattle", ayahs: 165, type: "Meccan" },
  { number: 7, name: "الأعراف", englishName: "Al-A'raf", urduName: "سورۃ الاعراف", englishMeaning: "The Heights", ayahs: 206, type: "Meccan" },
  { number: 8, name: "الأنفال", englishName: "Al-Anfal", urduName: "سورۃ الانفال", englishMeaning: "The Spoils of War", ayahs: 75, type: "Medinan" },
  { number: 9, name: "التوبة", englishName: "At-Tawbah", urduName: "سورۃ التوبہ", englishMeaning: "The Repentance", ayahs: 129, type: "Medinan" },
  { number: 10, name: "يونس", englishName: "Yunus", urduName: "سورۃ یونس", englishMeaning: "Jonah", ayahs: 109, type: "Meccan" },
  { number: 11, name: "هود", englishName: "Hud", urduName: "سورۃ ہود", englishMeaning: "Hud", ayahs: 123, type: "Meccan" },
  { number: 12, name: "يوسف", englishName: "Yusuf", urduName: "سورۃ یوسف", englishMeaning: "Joseph", ayahs: 111, type: "Meccan" },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", urduName: "سورۃ الرعد", englishMeaning: "The Thunder", ayahs: 43, type: "Medinan" },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", urduName: "سورۃ ابراہیم", englishMeaning: "Abraham", ayahs: 52, type: "Meccan" },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", urduName: "سورۃ الحجر", englishMeaning: "The Rocky Tract", ayahs: 99, type: "Meccan" },
  { number: 16, name: "النحل", englishName: "An-Nahl", urduName: "سورۃ النحل", englishMeaning: "The Bee", ayahs: 128, type: "Meccan" },
  { number: 17, name: "الإسراء", englishName: "Al-Isra", urduName: "سورۃ الاسراء", englishMeaning: "The Night Journey", ayahs: 111, type: "Meccan" },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", urduName: "سورۃ الکہف", englishMeaning: "The Cave", ayahs: 110, type: "Meccan" },
  { number: 19, name: "مريم", englishName: "Maryam", urduName: "سورۃ مریم", englishMeaning: "Mary", ayahs: 98, type: "Meccan" },
  { number: 20, name: "طه", englishName: "Ta-Ha", urduName: "سورۃ طٰہٰ", englishMeaning: "Ta-Ha", ayahs: 135, type: "Meccan" },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", urduName: "سورۃ الانبیاء", englishMeaning: "The Prophets", ayahs: 112, type: "Meccan" },
  { number: 22, name: "الحج", englishName: "Al-Hajj", urduName: "سورۃ الحج", englishMeaning: "The Pilgrimage", ayahs: 78, type: "Medinan" },
  { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", urduName: "سورۃ المومنون", englishMeaning: "The Believers", ayahs: 118, type: "Meccan" },
  { number: 24, name: "النور", englishName: "An-Nur", urduName: "سورۃ النور", englishMeaning: "The Light", ayahs: 64, type: "Medinan" },
  { number: 25, name: "الفرقان", englishName: "Al-Furqan", urduName: "سورۃ الفرقان", englishMeaning: "The Criterion", ayahs: 77, type: "Meccan" },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", urduName: "سورۃ الشعراء", englishMeaning: "The Poets", ayahs: 227, type: "Meccan" },
  { number: 27, name: "النمل", englishName: "An-Naml", urduName: "سورۃ النمل", englishMeaning: "The Ant", ayahs: 93, type: "Meccan" },
  { number: 28, name: "القصص", englishName: "Al-Qasas", urduName: "سورۃ القصص", englishMeaning: "The Stories", ayahs: 88, type: "Meccan" },
  { number: 29, name: "العنكبوت", englishName: "Al-'Ankabut", urduName: "سورۃ العنکبوت", englishMeaning: "The Spider", ayahs: 69, type: "Meccan" },
  { number: 30, name: "الروم", englishName: "Ar-Rum", urduName: "سورۃ الروم", englishMeaning: "The Romans", ayahs: 60, type: "Meccan" },
  { number: 31, name: "لقمان", englishName: "Luqman", urduName: "سورۃ لقمان", englishMeaning: "Luqman", ayahs: 34, type: "Meccan" },
  { number: 32, name: "السجدة", englishName: "As-Sajdah", urduName: "سورۃ السجدہ", englishMeaning: "The Prostration", ayahs: 30, type: "Meccan" },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", urduName: "سورۃ الاحزاب", englishMeaning: "The Combined Forces", ayahs: 73, type: "Medinan" },
  { number: 34, name: "سبأ", englishName: "Saba", urduName: "سورۃ سبا", englishMeaning: "Sheba", ayahs: 54, type: "Meccan" },
  { number: 35, name: "فاطر", englishName: "Fatir", urduName: "سورۃ فاطر", englishMeaning: "Originator", ayahs: 45, type: "Meccan" },
  { number: 36, name: "يس", englishName: "Ya-Sin", urduName: "سورۃ یٰسین", englishMeaning: "Ya Sin", ayahs: 83, type: "Meccan" },
  { number: 37, name: "الصافات", englishName: "As-Saffat", urduName: "سورۃ الصافات", englishMeaning: "Those who set the Ranks", ayahs: 182, type: "Meccan" },
  { number: 38, name: "ص", englishName: "Sad", urduName: "سورۃ صٓ", englishMeaning: "The Letter Sad", ayahs: 88, type: "Meccan" },
  { number: 39, name: "الزمر", englishName: "Az-Zumar", urduName: "سورۃ الزمر", englishMeaning: "The Troops", ayahs: 75, type: "Meccan" },
  { number: 40, name: "غافر", englishName: "Ghafir", urduName: "سورۃ غافر", englishMeaning: "The Forgiver", ayahs: 85, type: "Meccan" },
  { number: 41, name: "فصلت", englishName: "Fussilat", urduName: "سورۃ فصلت", englishMeaning: "Explained in Detail", ayahs: 54, type: "Meccan" },
  { number: 42, name: "الشورى", englishName: "Ash-Shura", urduName: "سورۃ الشوریٰ", englishMeaning: "The Consultation", ayahs: 53, type: "Meccan" },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", urduName: "سورۃ الزخرف", englishMeaning: "The Ornaments of Gold", ayahs: 89, type: "Meccan" },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhan", urduName: "سورۃ الدخان", englishMeaning: "The Smoke", ayahs: 59, type: "Meccan" },
  { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", urduName: "سورۃ الجاثیہ", englishMeaning: "The Crouching", ayahs: 37, type: "Meccan" },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", urduName: "سورۃ الاحقاف", englishMeaning: "The Wind-Curved Sandhills", ayahs: 35, type: "Meccan" },
  { number: 47, name: "محمد", englishName: "Muhammad", urduName: "سورۃ محمد", englishMeaning: "Muhammad", ayahs: 38, type: "Medinan" },
  { number: 48, name: "الفتح", englishName: "Al-Fath", urduName: "سورۃ الفتح", englishMeaning: "The Victory", ayahs: 29, type: "Medinan" },
  { number: 49, name: "الحجرات", englishName: "Al-Hujurat", urduName: "سورۃ الحجرات", englishMeaning: "The Rooms", ayahs: 18, type: "Medinan" },
  { number: 50, name: "ق", englishName: "Qaf", urduName: "سورۃ قٓ", englishMeaning: "The Letter Qaf", ayahs: 45, type: "Meccan" },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", urduName: "سورۃ الذاریات", englishMeaning: "The Winnowing Winds", ayahs: 60, type: "Meccan" },
  { number: 52, name: "الطور", englishName: "At-Tur", urduName: "سورۃ الطور", englishMeaning: "The Mount", ayahs: 49, type: "Meccan" },
  { number: 53, name: "النجم", englishName: "An-Najm", urduName: "سورۃ النجم", englishMeaning: "The Star", ayahs: 62, type: "Meccan" },
  { number: 54, name: "القمر", englishName: "Al-Qamar", urduName: "سورۃ القمر", englishMeaning: "The Moon", ayahs: 55, type: "Meccan" },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahman", urduName: "سورۃ الرحمٰن", englishMeaning: "The Beneficent", ayahs: 78, type: "Medinan" },
  { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", urduName: "سورۃ الواقعہ", englishMeaning: "The Inevitable", ayahs: 96, type: "Meccan" },
  { number: 57, name: "الحديد", englishName: "Al-Hadid", urduName: "سورۃ الحدید", englishMeaning: "The Iron", ayahs: 29, type: "Medinan" },
  { number: 58, name: "المجادلة", englishName: "Al-Mujadila", urduName: "سورۃ المجادلہ", englishMeaning: "The Pleading Woman", ayahs: 22, type: "Medinan" },
  { number: 59, name: "الحشر", englishName: "Al-Hashr", urduName: "سورۃ الحشر", englishMeaning: "The Exile", ayahs: 24, type: "Medinan" },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", urduName: "سورۃ الممتحنہ", englishMeaning: "She that is to be examined", ayahs: 13, type: "Medinan" },
  { number: 61, name: "الصف", englishName: "As-Saf", urduName: "سورۃ الصف", englishMeaning: "The Ranks", ayahs: 14, type: "Medinan" },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", urduName: "سورۃ الجمعہ", englishMeaning: "The Congregation, Friday", ayahs: 11, type: "Medinan" },
  { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", urduName: "سورۃ المنافقون", englishMeaning: "The Hypocrites", ayahs: 11, type: "Medinan" },
  { number: 64, name: "التغابن", englishName: "At-Taghabun", urduName: "سورۃ التغابن", englishMeaning: "The Mutual Disillusion", ayahs: 18, type: "Medinan" },
  { number: 65, name: "الطلاق", englishName: "At-Talaq", urduName: "سورۃ الطلاق", englishMeaning: "The Divorce", ayahs: 12, type: "Medinan" },
  { number: 66, name: "التحريم", englishName: "At-Tahrim", urduName: "سورۃ التحریم", englishMeaning: "The Prohibition", ayahs: 12, type: "Medinan" },
  { number: 67, name: "الملك", englishName: "Al-Mulk", urduName: "سورۃ الملک", englishMeaning: "The Sovereignty", ayahs: 30, type: "Meccan" },
  { number: 68, name: "القلم", englishName: "Al-Qalam", urduName: "سورۃ القلم", englishMeaning: "The Pen", ayahs: 52, type: "Meccan" },
  { number: 69, name: "الحاقة", englishName: "Al-Haqqah", urduName: "سورۃ الحاقہ", englishMeaning: "The Reality", ayahs: 52, type: "Meccan" },
  { number: 70, name: "المعارج", englishName: "Al-Ma'arij", urduName: "سورۃ المعارج", englishMeaning: "The Ascending Stairways", ayahs: 44, type: "Meccan" },
  { number: 71, name: "نوح", englishName: "Nuh", urduName: "سورۃ نوح", englishMeaning: "Noah", ayahs: 28, type: "Meccan" },
  { number: 72, name: "الجن", englishName: "Al-Jinn", urduName: "سورۃ الجن", englishMeaning: "The Jinn", ayahs: 28, type: "Meccan" },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil", urduName: "سورۃ المزمل", englishMeaning: "The Enshrouded One", ayahs: 20, type: "Meccan" },
  { number: 74, name: "المدثر", englishName: "Al-Muddaththir", urduName: "سورۃ المدثر", englishMeaning: "The Cloaked One", ayahs: 56, type: "Meccan" },
  { number: 75, name: "القيامة", englishName: "Al-Qiyamah", urduName: "سورۃ القیامہ", englishMeaning: "The Resurrection", ayahs: 40, type: "Meccan" },
  { number: 76, name: "الإنسان", englishName: "Al-Insan", urduName: "سورۃ الانسان", englishMeaning: "The Man", ayahs: 31, type: "Medinan" },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalat", urduName: "سورۃ المرسلات", englishMeaning: "The Emissaries", ayahs: 50, type: "Meccan" },
  { number: 78, name: "النبأ", englishName: "An-Naba", urduName: "سورۃ النبا", englishMeaning: "The Tidings", ayahs: 40, type: "Meccan" },
  { number: 79, name: "النازعات", englishName: "An-Nazi'at", urduName: "سورۃ النازعات", englishMeaning: "Those who drag forth", ayahs: 46, type: "Meccan" },
  { number: 80, name: "عبس", englishName: "Abasa", urduName: "سورۃ عبس", englishMeaning: "He Frowned", ayahs: 42, type: "Meccan" },
  { number: 81, name: "التكوير", englishName: "At-Takwir", urduName: "سورۃ التکویر", englishMeaning: "The Overthrowing", ayahs: 29, type: "Meccan" },
  { number: 82, name: "الانفطار", englishName: "Al-Infitar", urduName: "سورۃ الانفطار", englishMeaning: "The Cleaving", ayahs: 19, type: "Meccan" },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", urduName: "سورۃ المطففین", englishMeaning: "The Defrauding", ayahs: 36, type: "Meccan" },
  { number: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", urduName: "سورۃ الانشقاق", englishMeaning: "The Sundering", ayahs: 25, type: "Meccan" },
  { number: 85, name: "البروج", englishName: "Al-Buruj", urduName: "سورۃ البروج", englishMeaning: "The Mansions of the Stars", ayahs: 22, type: "Meccan" },
  { number: 86, name: "الطارق", englishName: "At-Tariq", urduName: "سورۃ الطارق", englishMeaning: "The Nightcommer", ayahs: 17, type: "Meccan" },
  { number: 87, name: "الأعلى", englishName: "Al-A'la", urduName: "سورۃ الاعلیٰ", englishMeaning: "The Most High", ayahs: 19, type: "Meccan" },
  { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", urduName: "سورۃ الغاشیہ", englishMeaning: "The Overwhelming", ayahs: 26, type: "Meccan" },
  { number: 89, name: "الفجر", englishName: "Al-Fajr", urduName: "سورۃ الفجر", englishMeaning: "The Dawn", ayahs: 30, type: "Meccan" },
  { number: 90, name: "البلد", englishName: "Al-Balad", urduName: "سورۃ البلد", englishMeaning: "The City", ayahs: 20, type: "Meccan" },
  { number: 91, name: "الشمس", englishName: "Ash-Shams", urduName: "سورۃ الشمس", englishMeaning: "The Sun", ayahs: 15, type: "Meccan" },
  { number: 92, name: "الليل", englishName: "Al-Layl", urduName: "سورۃ اللیل", englishMeaning: "The Night", ayahs: 21, type: "Meccan" },
  { number: 93, name: "الضحى", englishName: "Ad-Duha", urduName: "سورۃ الضحٰی", englishMeaning: "The Morning Hours", ayahs: 11, type: "Meccan" },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh", urduName: "سورۃ الشرح", englishMeaning: "The Relief", ayahs: 8, type: "Meccan" },
  { number: 95, name: "التين", englishName: "At-Tin", urduName: "سورۃ التین", englishMeaning: "The Fig", ayahs: 8, type: "Meccan" },
  { number: 96, name: "العلق", englishName: "Al-'Alaq", urduName: "سورۃ العلق", englishMeaning: "The Clot", ayahs: 19, type: "Meccan" },
  { number: 97, name: "القدر", englishName: "Al-Qadr", urduName: "سورۃ القدر", englishMeaning: "The Power", ayahs: 5, type: "Meccan" },
  { number: 98, name: "البينة", englishName: "Al-Bayyinah", urduName: "سورۃ البینہ", englishMeaning: "The Clear Proof", ayahs: 8, type: "Medinan" },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", urduName: "سورۃ الزلزلہ", englishMeaning: "The Earthquake", ayahs: 8, type: "Medinan" },
  { number: 100, name: "العاديات", englishName: "Al-'Adiyat", urduName: "سورۃ العادیات", englishMeaning: "The Courser", ayahs: 11, type: "Meccan" },
  { number: 101, name: "القارعة", englishName: "Al-Qari'ah", urduName: "سورۃ القارعہ", englishMeaning: "The Calamity", ayahs: 11, type: "Meccan" },
  { number: 102, name: "التكاثر", englishName: "At-Takathur", urduName: "سورۃ التکاثر", englishMeaning: "The Rivalry in World Increase", ayahs: 8, type: "Meccan" },
  { number: 103, name: "العصر", englishName: "Al-'Asr", urduName: "سورۃ العصر", englishMeaning: "The Declining Day", ayahs: 3, type: "Meccan" },
  { number: 104, name: "الهمزة", englishName: "Al-Humazah", urduName: "سورۃ الہمزہ", englishMeaning: "The Traducer", ayahs: 9, type: "Meccan" },
  { number: 105, name: "الفيل", englishName: "Al-Fil", urduName: "سورۃ الفیل", englishMeaning: "The Elephant", ayahs: 5, type: "Meccan" },
  { number: 106, name: "قريش", englishName: "Quraysh", urduName: "سورۃ قریش", englishMeaning: "Quraysh", ayahs: 4, type: "Meccan" },
  { number: 107, name: "الماعون", englishName: "Al-Ma'un", urduName: "سورۃ الماعون", englishMeaning: "The Small Kindnesses", ayahs: 7, type: "Meccan" },
  { number: 108, name: "الكوثر", englishName: "Al-Kawthar", urduName: "سورۃ الکوثر", englishMeaning: "The Abundance", ayahs: 3, type: "Meccan" },
  { number: 109, name: "الكافرون", englishName: "Al-Kafirun", urduName: "سورۃ الکافرون", englishMeaning: "The Disbelievers", ayahs: 6, type: "Meccan" },
  { number: 110, name: "النصر", englishName: "An-Nasr", urduName: "سورۃ النصر", englishMeaning: "The Divine Support", ayahs: 3, type: "Medinan" },
  { number: 111, name: "المسد", englishName: "Al-Masad", urduName: "سورۃ المسد", englishMeaning: "The Palm Fibre", ayahs: 5, type: "Meccan" },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", urduName: "سورۃ الاخلاص", englishMeaning: "The Sincerity", ayahs: 4, type: "Meccan" },
  { number: 113, name: "الفلق", englishName: "Al-Falaq", urduName: "سورۃ الفلق", englishMeaning: "The Daybreak", ayahs: 5, type: "Meccan" },
  { number: 114, name: "الناس", englishName: "An-Nas", urduName: "سورۃ الناس", englishMeaning: "The Mankind", ayahs: 6, type: "Meccan" },
];

// Surahs with Muqatta'at (حروف مقطعات) - must be on separate line
export const MUQATTAAT_SURAHS: Record<number, string> = {
  2: "الٓمٓ",
  3: "الٓمٓ",
  7: "الٓمٓصٓ",
  10: "الٓرٰ",
  11: "الٓرٰ",
  12: "الٓرٰ",
  13: "الٓمٓرٰ",
  14: "الٓرٰ",
  15: "الٓرٰ",
  19: "كٓهٰيٰعٓصٓ",
  20: "طٰهٰ",
  26: "طٰسٓمٓ",
  27: "طٰسٓ",
  28: "طٰسٓمٓ",
  29: "الٓمٓ",
  30: "الٓمٓ",
  31: "الٓمٓ",
  32: "الٓمٓ",
  36: "يٰسٓ",
  38: "صٓ",
  40: "حٰمٓ",
  41: "حٰمٓ",
  42: "حٰمٓ عٓسٓقٓ",
  43: "حٰمٓ",
  44: "حٰمٓ",
  45: "حٰمٓ",
  46: "حٰمٓ",
  50: "قٓ",
  68: "نٓ",
};
